services:
  backend-service:
    build:
      context: ./services/backend-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/backend-service/src:/app
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
      - CORS_ORIGINS=["http://localhost:3000"]
    command: python main.py